[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "cd frontend && npm ci --legacy-peer-deps",
  "cd ../backend && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd ../backend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/"
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_ENV = "production"
