[phases.setup]
nixPkgs = ["nodejs-22_x", "python3"]

[phases.install]
cmds = [
  # Install root workspace deps (if any)
  "npm ci --omit=dev --legacy-peer-deps || npm ci --legacy-peer-deps",
  # Install frontend deps using absolute path
  "cd /app/frontend && npm ci --legacy-peer-deps || true",
  # Install backend deps using absolute path (include dev for build)
  "cd /app/backend && npm ci --include=dev --legacy-peer-deps || npm ci --include=dev"
]

[phases.build]
cmds = [
  # Build frontend first with compatible Node
  "cd /app/frontend && npm run build",
  # Build backend and copy frontend output into backend/public
  "cd /app/backend && npm run build",
  "mkdir -p /app/backend/public",
  "cp -r /app/frontend/dist/* /app/backend/public/ || true"
]

[start]
cmd = "cd /app/backend && node dist/index.js"

[variables]
NODE_ENV = "production"
