[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
cmds = [
  "cd backend",
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd backend",
  "npm run build"
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_ENV = "production"
