[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "cd frontend && npm ci --legacy-peer-deps",
  "cd /app/backend && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd /app/frontend && npm run build",
  "cd /app/backend && npm run build",
  "mkdir -p /app/backend/public",
  "cp -r /app/frontend/dist/* /app/backend/public/"
]

[start]
cmd = "cd /app/backend && node dist/index.js"

[variables]
NODE_ENV = "production"
