apiVersion: apps/v1
kind: Deployment
metadata:
  name: hafjet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hafjet-frontend
  template:
    metadata:
      labels:
        app: hafjet-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/2024866732/hafjet-bukku-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: hafjet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
