# Reusable step: check for optional secrets and expose outputs
# Usage: call as a reusable workflow step via `uses: ./.github/workflows/ci-templates/secret-check.yml`
# The step will set outputs: ghcrpat_present, kubeconfig_present
# Example in a workflow:
# - uses: ./.github/workflows/ci-templates/secret-check.yml
#   id: secretcheck
# - name: Use cache only if GHCR
#   if: steps.secretcheck.outputs.ghcrpat_present == 'true'
#   run: echo "ghcr present"

on: [workflow_call]

jobs:
  secret_check:
    runs-on: ubuntu-latest
    outputs:
      ghcrpat_present: ${{ steps.check.outputs.ghcrpat }}
      kubeconfig_present: ${{ steps.check.outputs.kubeconfig }}
    steps:
      - name: Check optional secrets
        id: check
        run: |
          echo "Checking optional secrets..."
          if [ -n "${{ secrets.GHCRPAT-}}" ]; then
            echo "ghcrpat=true" >> $GITHUB_OUTPUT
          else
            echo "ghcrpat=false" >> $GITHUB_OUTPUT
          fi
          if [ -n "${{ secrets.KUBECONFIG-}}" ]; then
            echo "kubeconfig=true" >> $GITHUB_OUTPUT
          else
            echo "kubeconfig=false" >> $GITHUB_OUTPUT
          fi
