// This file is generated by the deployment automation to ensure a minimal
// frontend index.html is available even if static files weren't copied into
// the container. It embeds the built index.html content as a string.
const INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>frontend</title>
    <script type="module" crossorigin src="/assets/index-79LI_bQh.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/rolldown-runtime-DGruFWvd.js">
    <link rel="modulepreload" crossorigin href="/assets/charts-CsPrSeQA.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-C1UjBRMx.js">
    <link rel="stylesheet" crossorigin href="/assets/index-Ci5VkmZK.css">
  </head>
  <body>
    <div id="root"></div>

  </body>
</html>`;

export default INDEX_HTML;
