global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hafjet-backend'
    static_configs:
      - targets: ['backend:3001']

  - job_name: 'node'
    static_configs:
      - targets: ['backend:3001']
