---
name: Auto Update Railway URLs (safe)

on:
  workflow_dispatch:
  # Optionally run after a successful deployment workflow (uncomment when ready)
  # workflow_run:
  #   workflows: ["Deploy to Railway"]
  #   types: [completed]


jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          echo "Checking repository secrets..."
          # Fail early if secrets are missing - make failure explicit so CI owner can fix
          if [ -z "${{ secrets.REPO_WRITE_TOKEN }}" ]; then
            echo "❌ Error: REPO_WRITE_TOKEN not set"; exit 1
          fi
          if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "❌ Error: RAILWAY_TOKEN not set"; exit 1
          fi
          echo "All required secrets present."

  update-railway-urls:
    needs: check-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install GH CLI
        run: |
          sudo apt-get update && sudo apt-get install -y gh

      - name: Fetch Railway domain(s)
        id: fetch
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "(placeholder) Query Railway API to list domains/services"
          # Example: use Railway CLI or API to discover deployed domain for backend
          # For now output a placeholder domain which will be used downstream
          DOMAIN=example-backend.railway.app
          echo "domain=$DOMAIN" >> $GITHUB_OUTPUT
      - name: Set repository secret RAILWAY_BACKEND_URL
        uses: peter-evans/create-or-update-secret@v2
        with:
          token: ${{ secrets.REPO_WRITE_TOKEN }}
          secret-name: RAILWAY_BACKEND_URL
          # Use the discovered domain to build the backend URL
          secret-value: https://${{ steps.fetch.outputs.domain }}
          visibility: repository

      - name: Report
        run: |
          echo "Auto-update completed. If this ran, repo secrets were updated."


