# =============================================================================
# DEPRECATED WORKFLOW - DO NOT USE
# =============================================================================
# This workflow has been replaced by: .github/workflows/deploy.yml
#
# This file contained LocalStack configurations which are no longer needed
# for Railway cloud deployment. It also had syntax issues with if: expressions.
#
# For current Railway deployment, use: .github/workflows/deploy.yml
# =============================================================================

name: "[DEPRECATED] CI/CD Deploy (Old LocalStack Version)"

# Disabled - only manual trigger to prevent accidental runs
on:
  workflow_dispatch:

jobs:
  deprecated-notice:
    name: Deprecation Notice
    runs-on: ubuntu-latest
    
    steps:
      - name: Show deprecation warning
        run: |
          echo "========================================"
          echo " WARNING: DEPRECATED WORKFLOW"
          echo "========================================"
          echo ""
          echo "This workflow is deprecated and should not be used."
          echo ""
          echo "Please use the current deployment workflow:"
          echo "  .github/workflows/deploy.yml"
          echo ""
          echo "This file will be removed in a future cleanup."
          echo ""
          echo "========================================"
          exit 1
