name: CI

on:
  push:
    branches: [ main, master ]
  pull_request: {}

jobs:
  setup-and-check:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
      redis:
        image: redis:7-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install root dependencies
        run: npm install

      - name: Backend install and typecheck
        working-directory: ./backend
        run: |
          npm ci --legacy-peer-deps
          npx tsc --noEmit

      - name: Backend run tests
        working-directory: ./backend
        continue-on-error: true
        run: npm test

      - name: Frontend install and build
        working-directory: ./frontend
        continue-on-error: true
        run: |
          npm ci --legacy-peer-deps
          npm run build --if-present

  docker-builds:
    runs-on: ubuntu-latest
    needs: setup-and-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        run: docker build -t hafjet-backend:ci --target runtime -f backend/Dockerfile backend

      - name: Build frontend image
        run: docker build -t hafjet-frontend:ci -f frontend/Dockerfile frontend
