name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm manual deploy'
        required: true
        default: ''

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check confirmation
        if: ${{ github.event.inputs.confirm != 'deploy' }}
        run: |
          echo "Manual deploy confirmation not provided. To confirm, run workflow and set 'confirm' to 'deploy'."
          exit 1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.28.0'

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          if [ -z "$KUBE_CONFIG" ]; then
            echo "KUBE_CONFIG secret not provided; cannot apply manifests"
            exit 1
          fi
          echo "$KUBE_CONFIG" | base64 --decode > kubeconfig
          mkdir -p $HOME/.kube
          mv kubeconfig $HOME/.kube/config

      - name: Apply k8s manifests
        run: |
          kubectl apply -f deploy/k8s
