# =============================================================================
# Monitor Deploy Workflow - Automated Issue Creation
# =============================================================================
# Workflow ini akan automatically create GitHub Issue jika deployment ke
# Railway failed. Ia berguna untuk notification dan tracking failures.
#
# Trigger: Setiap kali "CI/CD Deploy to Railway" workflow selesai
# Action: Create issue jika conclusion != success
#
# Note: Menggunakan Actions GITHUB_TOKEN (built-in) - tiada setup tambahan
# =============================================================================

name: Monitor Deploy Workflow

on:
  workflow_run:
    workflows: ["CI/CD Deploy to Railway"]
    types:
      - completed

jobs:
  create-issue-on-failure:
    name: Create Issue on Deploy Failure
    runs-on: ubuntu-latest
    
    if: github.event.workflow_run.conclusion != 'success'
    
    steps:
      # -------------------------------------------------------------------------
      # Step 1: Checkout repository (diperlukan untuk gh CLI)
      # -------------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------------------------------
      # Step 2: Prepare issue body content
      # -------------------------------------------------------------------------
      - name: Prepare issue content
        id: prepare
        run: |
          cat > issue-body.md << 'ISSUE_EOF'
          ## 🚨 Railway Deployment Failed
          
          **Workflow Run:** ${{ github.event.workflow_run.html_url }}
          
          **Details:**
          - Commit SHA: `${{ github.event.workflow_run.head_sha }}`
          - Branch: `${{ github.event.workflow_run.head_branch }}`
          - Triggered by: @${{ github.event.workflow_run.triggering_actor.login }}
          - Conclusion: `${{ github.event.workflow_run.conclusion }}`
          - Run ID: `${{ github.event.workflow_run.id }}`
          
          **Next Steps:**
          1. Review the [workflow logs](${{ github.event.workflow_run.html_url }})
          2. Check Railway dashboard for deployment errors
          3. Verify all required secrets are set correctly
          4. Fix issues and push to trigger new deployment
          
          ---
          
          _This issue was automatically created by the Monitor Deploy workflow._
          ISSUE_EOF
          
          cat issue-body.md

      # -------------------------------------------------------------------------
      # Step 3: Create GitHub Issue using official action
      # -------------------------------------------------------------------------
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const issueBody = fs.readFileSync('issue-body.md', 'utf8');
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Railway Deploy Failed - ${context.payload.workflow_run.head_sha.substring(0, 7)}`,
              body: issueBody,
              labels: ['ci', 'deployment', 'automated', 'bug']
            });
            
            console.log(`Created issue #${issue.data.number}`);
