name: Backup Restore Verify

on:
  # Disabled scheduled runs - can be run manually if needed
  # schedule:
  #   - cron: '0 3 * * 0' # Weekly on Sunday at 03:00 UTC
  workflow_dispatch: {}  # Manual trigger only

jobs:
  restore-verify:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..30}; do
            if mongosh --eval "db.adminCommand('ping')" --quiet localhost:27017/admin; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Attempt $i: MongoDB not ready yet, waiting..."
            sleep 2
          done
          echo "MongoDB failed to become ready"
          exit 1

      - name: Run backup-restore test
        run: |
          cd backend
          npm run test:backup-restore
        continue-on-error: false

      - name: Upload artifacts (logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-restore-logs-${{ github.run_id }}
          path: |
            backend/backups/**
            backend/*.log
          if-no-files-found: warn
