name: Validate Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    name: Validate GitHub workflow YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pyyaml
        run: python -m pip install --upgrade pip pyyaml

      - name: Parse and validate workflow YAML files
        run: |
          python - <<'PY'
          import glob, sys, yaml
          files = glob.glob('.github/workflows/*.yml') + glob.glob('.github/workflows/*.yaml')
          if not files:
              print('No workflow files found; nothing to validate.')
              sys.exit(0)
          had_error = False
          for f in files:
              try:
                  with open(f, 'r', encoding='utf-8') as fh:
                      # Load all documents to catch multi-doc YAML issues
                      list(yaml.safe_load_all(fh))
              except Exception as e:
                  print(f'ERROR parsing {f}: {e}', file=sys.stderr)
                  had_error = True
          if had_error:
              sys.exit(1)
          print('All workflow YAML files parsed successfully.')
          PY
